=== laci6599/LWI9Z1xmlGyak/Beadandó/DOM program/src/hu/domparse/LWI9Z1/XMLSchemaLWI9Z1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="theatre" xmlns="theatre">
<xs:element name="data">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element name="theatre">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element name="address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:float" name="zipcode"/>
                    <xs:element type="xs:string" name="country"/>
                    <xs:element type="xs:string" name="city"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id"/>
            <xs:attribute type="xs:string" name="principalid"/>
            <xs:attribute type="xs:string" name="showid"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="principal">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="show" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:string" name="genre"/>
              <xs:element type="xs:string" name="length"/>
              <xs:element type="xs:string" name="director"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
            <xs:attribute type="xs:string" name="actorid" use="optional"/>
            <xs:attribute type="xs:string" name="ticketid" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="actor">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element name="datedata">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="dateplace"/>
                    <xs:element type="xs:date" name="datetime"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="dramagroup"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="ticket" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="category"/>
              <xs:element type="xs:float" name="price"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== laci6599/LWI9Z1xmlGyak/Beadandó/DOM program/src/hu/domparse/LWI9Z1/XMLlwi9z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="XMLSchemaLWI9Z1.xsd">
	
    <theatre id="theatre1" principalid="principal1" showid="show1">
		<name>
			Miskolci Nemzeti Színház
		</name>
		<address>
			<zipcode>
				3525
			</zipcode>
			<country>
				Magyarország
			</country>
			<city>
				Miskolc
			</city>
		</address>
	</theatre>

	<principal id="principal1">
		<name>
			Béres Attila
		</name>
	</principal>
    
	<show id="show1" actorid="actor1" ticketid="ticket1">
		<title>
			Cirkuszhercegnő
		</title>
		<genre>
			operett
		</genre>
		<length>
			185 perc
		</length>
		<director>
			Szabó Máté
		</director>
	</show>
	<show id="show2" actorid="actor2" ticketid="ticket2">
		<title>
			A velencei kalmár
		</title>
		<genre>
			vígjáték
		</genre>
		<length>
			200 perc
		</length>
		<director>
			Mohácsi János
		</director>
	</show>
	<show id="show3" actorid="actor3" ticketid="ticket3">
		<title>
			Hegedűs a háztetőn
		</title>
		<genre>
			musical
		</genre>
		<length>
			185 perc
		</length>
		<director>
			Béres Attila
		</director>
	</show>
	
	<actor id="actor1">
        <name>
			Papp Endre
		</name>
		<datedata>
			<dateplace>
				Debrecen
			</dateplace>
			<datetime>
				1993-10-03
			</datetime>
		</datedata>
        <dramagroup>
			színművész
		</dramagroup>
	</actor>
	<actor id="actor2">
        <name>
			Rózsa Krisztián
		</name>
		<datedata>
			<dateplace>
				Vásárosnamény
			</dateplace>
			<datetime>
				1991-07-26
			</datetime>
		</datedata>
        <dramagroup>
			színművész
		</dramagroup>
	</actor>
    <actor id="actor3">
        <name>
			Prohászka Fanni
		</name>
		<datedata>
			<dateplace>
				Budapest
			</dateplace>
			<datetime>
				1993-07-23
			</datetime>
		</datedata>
        <dramagroup>
			színművésznő
		</dramagroup>
	</actor>

	<ticket id="ticket1">
		<category>
			A
		</category>
        <price>
			2400
		</price>
	</ticket>
	<ticket id="ticket2">
		<category>
			B
		</category>
        <price>
			2700
		</price>
	</ticket>
	<ticket id="ticket3">
		<category>
			C
		</category>
        <price>
			3000
		</price>
	</ticket>

</data>

=== laci6599/LWI9Z1xmlGyak/Beadandó/DOM program/src/hu/domparse/LWI9Z1/XMLlwi9z1.updated.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><data xmlns="theatre" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="theatre XMLSchemaLWI9Z1.xsd">
    
    <theatre id="theatre1" principalid="principal1" showid="show1">
		<name>
			Miskolci Nemzeti Színház
		</name>
		<address>
			<zipcode>
				3525
			</zipcode>
			<country>
				Magyarország
			</country>
			<city>
				Miskolc
			</city>
		</address>
	</theatre>

	<principal id="principal1">
		<name>
			Béres Attila
		</name>
	</principal>
    
	<show actorid="actor1" id="show1" ticketid="ticket1">
		<title>
			Cirkuszhercegnő
		</title>
		<genre>
			operett
		</genre>
		<length>
			185 perc
		</length>
		<director>
			Szabó Máté
		</director>
	</show>
	<show actorid="actor2" id="show2" ticketid="ticket2">
		<title>
			A velencei kalmár
		</title>
		<genre>
			vígjáték
		</genre>
		<length>
			200 perc
		</length>
		<director>
			Mohácsi János
		</director>
	</show>
	<show actorid="actor3" id="show3" ticketid="ticket3">
		<title>Modify</title>
		<genre>Más</genre>
		<length>100 perc</length>
		<director>Új rendező</director>
	</show>
	
	<actor id="actor1">
        <name>
			Papp Endre
		</name>
		<datedata>
			<dateplace>
				Debrecen
			</dateplace>
			<datetime>
				1993-10-03
			</datetime>
		</datedata>
        <dramagroup>
			színművész
		</dramagroup>
	</actor>
	<actor id="actor2">
        <name>
			Rózsa Krisztián
		</name>
		<datedata>
			<dateplace>
				Vásárosnamény
			</dateplace>
			<datetime>
				1991-07-26
			</datetime>
		</datedata>
        <dramagroup>
			színművész
		</dramagroup>
	</actor>
    <actor id="actor3">
        <name>
			Prohászka Fanni
		</name>
		<datedata>
			<dateplace>
				Budapest
			</dateplace>
			<datetime>
				1993-07-23
			</datetime>
		</datedata>
        <dramagroup>
			színművésznő
		</dramagroup>
	</actor>

	<ticket id="ticket1">
		<category>
			A
		</category>
        <price>
			2400
		</price>
	</ticket>
	<ticket id="ticket2">
		<category>
			B
		</category>
        <price>
			2700
		</price>
	</ticket>
	<ticket id="ticket3">
		<category>
			C
		</category>
        <price>
			3000
		</price>
	</ticket>

</data>
